CREATE DATABASE QUANLYBDS_PC07859
GO

USE QUANLYBDS_PC07859
GO

-- Tạo bảng văn phòng
CREATE table VANPHONG (
	MaVP VARCHAR(7) NOT NULL,
	TenVP NVARCHAR(50) NOT NULL UNIQUE, --UNIQUE ĐỂ TẠO RÀNG BUỘC DUY NHẤT
	TRUONGPHONG VARCHAR(7)
)
GO

-- TẠO BẢNG NHÂN VIÊN
CREATE table NHANVIEN (
	MaNV VARCHAR(7) NOT NULL,
	Ten NVARCHAR(50) NOT NULL UNIQUE,
	MaVP VARCHAR(7)
)
GO

CREATE table DIADIEM (
	MaDD VARCHAR(7) NOT NULL,
	TenDD NVARCHAR(50) NOT NULL UNIQUE,
)
GO

CREATE table CO (
	MaVP VARCHAR(7),
	MaDD VARCHAR(7)
)
GO

CREATE table THANNHAN (
	Ten NVARCHAR(50) NOT NULL,
	NgaySinh DATE,
	MLH NVARCHAR(50),
	MaTN VARCHAR(7) NOT NULL
)
GO

CREATE table THUOC (
	MaNV VARCHAR(7),
	MaTN VARCHAR(7)
)
GO

CREATE table CSH (
	MaCSH VARCHAR(7) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50),
	SDT CHAR(12) CHECK (LEN(SDT) = 12 AND SDT NOT LIKE '%[^0-9]%')
)
GO

CREATE table BDS (
	MaBDS VARCHAR(7) NOT NULL,
	DiaChi NVARCHAR(50),
	MaCSH VARCHAR(7),
	MaVP VARCHAR(7)
)
GO

--Tạo khóa chính
	ALTER table VANPHONG ADD CONSTRAINT PK_MaVP PRIMARY KEY (MaVP)
	ALTER table NHANVIEN ADD CONSTRAINT PK_MaNV PRIMARY KEY (MaNV)
	ALTER table DIADIEM ADD CONSTRAINT PK_MaDD PRIMARY KEY (MaDD)

	ALTER table CO ALTER COLUMN MaVP VARCHAR(7) NOT NULL
	ALTER table CO ALTER COLUMN MaDD VARCHAR(7) NOT NULL
	ALTER table CO ADD CONSTRAINT PK_CO PRIMARY KEY (MaVP, MaDD)

	ALTER table BDS ADD CONSTRAINT PK_BDS PRIMARY KEY (MaBDS)
	ALTER table CSH ADD CONSTRAINT PK_CSH PRIMARY KEY (MaCSH)

	ALTER table THUOC ALTER COLUMN MaNV VARCHAR(7) NOT NULL
	ALTER table THUOC ALTER COLUMN MaTN VARCHAR(7) NOT NULL
	ALTER table THUOC ADD CONSTRAINT PK_THUOC PRIMARY KEY (MaNV, MaTN)

	ALTER table THANNHAN ADD CONSTRAINT PK_THANNHAN PRIMARY KEY (MaTN)

--Tạo khóa ngoại
	ALTER table NHANVIEN ADD CONSTRAINT FK_NHANVIEN_VANPHONG FOREIGN KEY (MaVP) REFERENCES VANPHONG (MaVP)
	ALTER table BDS ADD CONSTRAINT FK_BDS_CSH FOREIGN KEY (MaCSH) REFERENCES CSH (MaCSH)
	ALTER table BDS ADD CONSTRAINT FK_BDS_VANPHONG FOREIGN KEY (MaVP) REFERENCES VANPHONG (MaVP)
	ALTER table CO ADD CONSTRAINT FK_CO_MaVP FOREIGN KEY (MaVP) REFERENCES VANPHONG (MaVP)
	ALTER table CO ADD CONSTRAINT FK_CO_MaDD FOREIGN KEY (MaDD) REFERENCES DIADIEM (MaDD)
	ALTER table THUOC ADD CONSTRAINT FK_THUOC_MaNV FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV)
	ALTER table THUOC ADD CONSTRAINT FK_THUOC_MaTN FOREIGN KEY (MaTN) REFERENCES THANNHAN (MaTN)

--Tạo ràng buộc
	ALTER table CSH ADD CONSTRAINT CSH_UNIQUE_SDT UNIQUE (SDT)



/* Thêm một cột:
ALTER TABLE tênbảng
ADD têncột 	kiểudữliệu;
Thay đổi kiểu dữ liệu cho cột:
ALTER TABLE tênbảng
ALTER COLUMN têncột   kiểudữliệu;
Xóa một cột:
ALTER TABLE tênbảng
DROP COLUMN têncột ; */

--Tạo bảng TEST1 có 3 cột: id, họ, tên
CREATE table TEST1 (
	ID VARCHAR(7),
	HO NVARCHAR(10),
	TEN NVARCHAR(30)
)
--Thêm một cột năm sinh vào bảng TEST1
	ALTER table TEST1 ADD NAMSINH INT

--Thay đổi kiểu dữ liệu cột HO thành NVARCHAR(20)
	ALTER table TEST1 ALTER COLUMN HO NVARCHAR(20)

--Xóa cột NAMSINH
	ALTER table TEST1 DROP COLUMN NAMSINH

--Thêm cột LUONG cho bảng TEST1. Viết ràng buộc để lương > 2000
	ALTER table TEST1 ADD LUONG FLOAT
	ALTER table TEST1 ADD CONSTRAINT CHECKLUONG CHECK(LUONG > 2000)
-- ALTER table TEST1 DROP CONSTRAINT CHECKLUONG / Xóa ràng buộc

--Tạo ràng buộc duy nhất cho cột TEN trong bảng TEST1
	ALTER table TEST1 ADD CONSTRAINT TEN_UNQ UNIQUE(TEN)

--Tạo khóa chính cho bảng TEST1
	ALTER table TEST1 ALTER COLUMN ID VARCHAR(7) NOT NULL
	ALTER table TEST1 ADD CONSTRAINT PK_TEST1 PRIMARY KEY (ID)

--Tạo bảng TEST2 gồm 2 cột: IDTEST2, ID, trong đó ID tham chiếu đến ID của TEST1
CREATE table TEST2 (
	IDTEST2 VARCHAR(10) PRIMARY KEY,
	ID VARCHAR(7)
)

--Khóa ngoại
	ALTER table TEST2 ADD CONSTRAINT FK_TEST1_TEST2 FOREIGN KEY (ID) REFERENCES TEST1 (ID)


