CREATE DATABASE QuanLyNhanVien;
GO

USE QuanLyNhanVien;
GO

CREATE TABLE PHONGBAN (
    PB_MA VARCHAR(10) PRIMARY KEY,
    PB_TEN NVARCHAR(20),
    PB_TRPHG NCHAR(20)
);
GO

CREATE TABLE NHANVIEN (
    NV_MA VARCHAR(10) PRIMARY KEY,
    NV_HO NVARCHAR(10),
    NV_TEN NVARCHAR(10),
    NV_NAMSINH INT,
    NV_DIACHI NVARCHAR(30),
    NV_GIOITINH NVARCHAR(5),
    NV_LUONG FLOAT,
    NV_PHG VARCHAR(10),
    FOREIGN KEY (NV_PHG) REFERENCES PHONGBAN(PB_MA)
);
GO
ALTER TABLE PHONGBAN ADD FOREIGN KEY(PB_TRPHG) REFERENCES NHANVIEN(NV_MA)
GO


CREATE TABLE DUAN (
    DA_MA VARCHAR(10) PRIMARY KEY,
    DA_TEN NVARCHAR(50),
    DA_NGAYBD INT,
    DA_NGAYKT INT
);
GO

CREATE TABLE QUANLYDUAN (
    QLDA_MADA VARCHAR(10),
    QLDA_MANV VARCHAR(10),
    QLDA_NGAYTG INT,
    QLDA_NGAYKT INT,
    QLDA_SOGIO FLOAT,
    QLDA_VAITRO NVARCHAR(50),
    PRIMARY KEY (QLDA_MADA, QLDA_MANV),
    FOREIGN KEY (QLDA_MADA) REFERENCES DUAN(DA_MA),
    FOREIGN KEY (QLDA_MANV) REFERENCES NHANVIEN(NV_MA)
);
GO