USE QLNHANVIEN
-- DUAN
SELECT *
FROM DU_AN

-- TENPB, MAPB
SELECT TEN_PB AS 'TÊN PHÒNG BAN', MA_PB AS 'MÃ PHÒNG BAN'
FROM PHONG_BAN

-- VIET CAU TRUY VAN HIỂN THỊ HỌ VÀ TÊN
SELECT HO_NV + ' ' + TEN_NV AS 'HỌ VÀ TÊN'
FROM NHAN_VIEN

--VIET CAU TRUY VAN HIỂN THỊ HỌ TÊN TUỔI NHÂN VIÊN
SELECT HO_NV + ' ' + TEN_NV AS 'HỌ VÀ TÊN', NGAY_SINH AS 'NGÀY SINH' , YEAR(GETDATE()) -YEAR(NGAY_SINH) AS 'TUỔI'
FROM NHAN_VIEN


-- VIẾT CÂU TRUY VẤN HIỂN THỊ HỌ CỦA NHÂN VIÊN KHÁC NHAU
SELECT DISTINCT HO_NV AS 'HỌ NHÂN VIÊN'
FROM NHAN_VIEN

-- VIẾT CÂU TRUY VẤN HIỂN THỊ THÔNG TIN NHÂN VIÊN
SELECT TOP 5 *
FROM NHAN_VIEN

-- VIẾT CÂU TRUY VẤN HIỂN THỊ THÔNG TIN NHÂN VIÊN CÓ LƯƠNG CAO NHẤT
SELECT TOP 5 *
FROM NHAN_VIEN 
ORDER BY LUONG DESC

-- VIẾT CÂU TRUY VẤN CÓ LƯƠNG THẤP NHẤT
SELECT TOP 1 WITH TIES *
FROM NHAN_VIEN
ORDER BY LUONG

-- WHERE

-- VIẾT CÂU TRUY VẤN HIỂN THỊ DANH SÁCH NHÂN VIÊN THUỘC PHÒNG BAN 001
SELECT * 
FROM NHAN_VIEN
WHERE PHG = 'PB001'

-- VIẾT CÂU TRUY VẤN NHÂN VIÊN HỌ ĐẦU BẮT ĐẦU BẰNG H, SAU ĐÓ LÀ 1 KÝ TỰ
SELECT * 
FROM NHAN_VIEN
WHERE HO_NV LIKE 'H_'


-- HIỂN THỊ NHÂN VIÊN CÓ TÊN CHỨA ANH
SELECT * 
FROM NHAN_VIEN
WHERE TEN_NV LIKE '%ANH%'


--LUONG > 900
SELECT HO_NV, TEN_NV, LUONG
FROM NHAN_VIEN
WHERE LUONG > 900

--LUONG >= 500 AND LUONG <= 1000
SELECT HO_NV, TEN_NV, LUONG
FROM NHAN_VIEN
WHERE LUONG BETWEEN 500 AND 1000

-- NHAN VIEN THUỘC PHG 1 VÀ PHG 4
-- C1
SELECT * 
FROM NHAN_VIEN
WHERE PHG = 'PB001' OR PHG = 'PB004'
-- C2 
SELECT * 
FROM NHAN_VIEN 
WHERE PHG IN('PB001', 'PB004')


-- DE AN THUỘC CHỮA CHUỖI SẢN PHẨM
SELECT *
FROM NHAN_VIEN
WHERE TEN_DUAN LIKE '%san pham%'


-- HIEN THI HO, TEN, LUONG CUA NHAN VIEN LUONG < 500 AND PHG = 'PB004'
SELECT HO_NV, TEN_NV, LUONG
FROM NHAN_VIEN
WHERE LUONG < 500 AND PHG = 'PB004'

-- LUONG < 30000 AND PHG = 'PB004'
SELECT *
FROM NHAN_VIEN
WHERE LUONG < 30000 AND PHG = 'PB004'

