CREATE DATABASE QLSHOW_PC07859
GO

USE QLSHOW_PC07859
GO

CREATE TABLE CONGTY(
	MACTY VARCHAR(10) NOT NULL,
	TENCTY NVARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY(MACTY)
)
GO

CREATE TABLE SHOW(
	STTSHOW VARCHAR(10) NOT NULL,
	NGAYBD DATE NOT NULL, 
	YNGHIA NVARCHAR(50),
	PRIMARY KEY(STTSHOW)
)
GO

CREATE TABLE TAITRO(
	STTSHOW VARCHAR(10) NOT NULL,
	MACTY VARCHAR(10) NOT NULL,
	SOTIEN MONEY,
	PRIMARY KEY(STTSHOW, MACTY),
	FOREIGN KEY(STTSHOW) REFERENCES SHOW(STTSHOW),
	FOREIGN KEY(MACTY) REFERENCES CONGTY(MACTY)	
)
GO

ALTER TABLE TAITRO ADD CONSTRAINT CHECKTIEN CHECK (SOTIEN >= 10000000);

INSERT INTO CONGTY
VALUES ('CTY1','MTP'),
	   ('CTY2','MTP ENTERTAINMENT')
GO


INSERT INTO SHOW
VALUES ('1', '08-08-2023', 'CAM ON MOI NGUOI'),
		('2', '09-09-2022', 'CAM ON TAT CAC MOI NGUOI')
GO

INSERT INTO TAITRO
VALUES ('1','CTY1',10000000),
		('2','CTY2',10000000)
GO
